# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gaVEm6IEn7D_b-_APWAASs8KzUCmx4JV
"""

!mkdir -p ~/.kaggle

!cp kaggle.json ~/.kaggle/

!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d mohitsingh1804/plantvillage

!unzip plantvillage.zip

import os

os.listdir()

len(os.listdir("PlantVillage"))
os.listdir("PlantVillage")

train_dir = "/content/PlantVillage/train"
val_dir   = "/content/PlantVillage/val"

from tensorflow.keras.preprocessing.image import ImageDataGenerator

img_size = (224, 224)
batch_size = 32

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=40,       # Increased from 20 to handle shaky hands
    width_shift_range=0.2,   # Moves image left/right (if leaf isn't centered)
    height_shift_range=0.2,  # Moves image up/down
    shear_range=0.2,         # Distorts image (different camera angles)
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'      # Fills in pixels lost during rotation/shifting
)

val_datagen = ImageDataGenerator(
    rescale=1./255
)

train_data = train_datagen.flow_from_directory(
    train_dir,
    target_size=img_size,
    batch_size=batch_size,
    class_mode='categorical'
)

val_data = val_datagen.flow_from_directory(
    val_dir,
    target_size=img_size,
    batch_size=batch_size,
    class_mode='categorical'
)

print("Classes:", train_data.num_classes)
print(train_data.class_indices)

